### ISSUE TITLE
strange word division

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#32]
Dear Charles,
We have this odd situation, where upama is breaking the śloka wrongly, collating ato against a word too early.  

![image](https://user-images.githubusercontent.com/762246/151098323-c27391c0-bccb-414a-92c9-0180da42567d.png)

This is at Suśruta, sūtrasthāna, 16.15 ([link](https://saktumiva.org/wiki/wujastyk/susrutasamhita/01-su.su/provisional-edition_sutrasthana?upama_ver=gv6fam6pom)).

Can you suggest how to fix this?
Thanks!
Dominik

**Comment by chchch** [comment]
Hmm I'm looking at the link and it looks like the edition reads `tato'nu` without a space, which might be affecting the collation.

The main problem though is probably that the algorithm is collating the `a` in `ato` with the `a` in `budhaḥ`. In general, I think this calls for tweaking the algorithm — I'll have to look into it for a bit, since `saktumiva` is currently using a fast algorithm which is less accurate than what I use for `helayo` (it's a tradeoff so that we can get instant results).

**Comment by wujastyk** [comment]
Thanks, Charles.  I'd fixed tato'nu earlier, but somehow failed to get the emended file uploaded to Saktumiva.  Now fixed.  But the collation is wonky in spite of the update.  Thank you for looking at this!

**Comment by chchch** [comment]
I just added a function that retunes the alignment at certain places; your passage looks like this now:

![image](https://user-images.githubusercontent.com/1082192/152699191-8742a408-7568-445b-85c3-85b041dd65de.png)

The apparatus should be better overall with the new code. It's still a little experimental, so let me know if you find anything weird.

**Comment by wujastyk** [comment]
Thank you, Charles.  The above alignments look just right.   We'll all
report back as we notice anything special.

If it can be explained in words of one syllable, what change did you make
to the algorithm?
Dominik

**Comment by chchch** [comment]
Hmm... one syllable words are pretty tough, but basically now the alignment algorithm does a "second pass", looking for things like:
```
budhaḥ tataḥ
ataḥ
```
where you have a space in either your base text or your variant reading. Then it tries to realign these small sections using a slower but more accurate algorithm, which gives you this:
```
budhaḥ tataḥ
--------ataḥ
```
So then it recognizes that it can split off `ataḥ` as a variant reading of `tataḥ`, and treat `budhaḥ` as an omission.

In the above example, it also found
```
anena mrakṣayet
snehenaitena yojayet
```
And was able to split that into two lemmata as well, because, in the second pass, it gets aligned as
```
-------anena mrakṣayet
snehenaitena --yojayet
```
The space lines up, so it recognizes that it should split them into two. Hope that makes sense!

**Comment by wujastyk** [comment]
Thank you charles, this is superb. Slower but more accurate is better, I think.
