### ISSUE TITLE
PURLs

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#36]
I will be publishing a translation of some text that I've edited in Saktumiva, but not the text edition itself, at least for now.  I would like to refer to the online edition.  How do you recommend this is done?  
It would be ideal to have a persistent URL, or even a DOI or ARK.  Is there any way to get this kind of stable, long-lasting reference?
Best,
Dominik

**Comment by chchch** [comment]
Hmm, I think since all your XML files are on GitHub, the best way to do it would be to link your GitHub repository to Zenodo and make a release there. Then you'll get a DOI for the most up-to-date version of your repo. If you make a GitHub Release, you can also get a DOI for a specific version of your XML files.

**Comment by wujastyk** [comment]
That's a great approach, Charles.  And the way Zenodo handles versions will
really help.  I hadn't thought about the Release idea, but it would make
sense to do that before I publish in print on the text.

Yesterday, I made an experiment with saving a screenshot from Saktumiva as
a PDF and uploading that to Zenodo.

   -

   http://doi.org/10.5281/zenodo.6466366


That suits my present purposes pretty well, but I think I'll add your
idea of the Github link too.

Best,

Dominik
