### ISSUE TITLE
Request for another <g> character

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#78]
Hi, Charles,

Could we add Newa sign final anusvāra to Saktumiva's list of special characters?  Perhaps 
`<g ref="#newa-sign-final-anusvara"/>`?
For reference, see:
* https://www.compart.com/en/unicode/U+11448#UNC_DB

Best,
Dominik

**Comment by chchch** [comment]
Hmm, I wonder if there's an ergonomic way to transliterate this, especially since the difference between a "normal" anusvāra and a "final" anusvāra also comes up in other scripts, such as Bengali. Here are some ideas:

ṃ_
<g rend="final">ṃ</g>

The first option might be nice and simple, and also reuse the underscore which is already used as a "separator" to break up consonant conjuncts, etc.

**Comment by wujastyk** [comment]
I guess ṃ_ would be okay.  It's a bit, how shall I say, inexplicit.   I now realize that my suggestion about a <g> code wasn't displayed in my first message above.

**Comment by wujastyk** [comment]
Shall we go with `<g ref="#newa-sign-final-anusvara">ṃ</g>`, then, which echoes the Unicode name?

**Comment by chchch** [comment]
Done.
